#include <stdafx.hpp>
#include <render/menu/localization.hpp>

namespace render::localization
{

namespace
{

std::atomic<id> g_current{id::en};

const std::unordered_map<std::string_view, const char *> &chinese()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // --- navigation -------------------------------------------------
        {"Aimbot", "自瞄"},
        {"Triggerbot", "扳机"},
        {"Visuals", "视觉"},
        {"Misc", "杂项"},

        // --- weapon group tabs ------------------------------------------
        {"Global", "通用"},
        {"Pistol", "手枪"},
        {"SMG", "冲锋枪"},
        {"Rifle", "步枪"},
        {"Shotgun", "霰弹枪"},
        {"Sniper", "狙击枪"},
        {"Heavy", "机枪"},

        // --- combat cards -----------------------------------------------
        {"TARGETING", "瞄准"},
        {"PENETRATION", "穿透"},
        {"VISUALIZATION", "可视化"},
        {"TRIGGERBOT CORE", "扳机核心"},
        {"ADVANCED MODE", "高级模式"},
        // This card holds Auto Stop / Early Auto Stop -- it is about stopping
        // before the shot, not about the movement features in Misc.
        {"MOVEMENT", "自动急停"},
        {"OVERRIDE SETTINGS", "覆盖设置"},

        // --- combat rows ------------------------------------------------
        {"Master Switch", "总开关"},
        {"Activation", "激活"},
        {"Activation Mode", "激活模式"},
        {"Hold", "按住"},
        {"Always On", "始终开启"},
        {"Toggle", "切换"},
        {"Damage Override", "伤害覆盖"},
        {"Override Damage", "替代伤害"},
        {"Checks", "条件"},
        {"Jump", "跳跃"},
        {"Flash", "闪光"},
        {"Airborne", "空中"},
        {"Flashed", "被闪"},
        {"Threshold", "阈值"},
        {"Smoke", "烟雾"},
        {"Walls", "墙壁"},
        {"Block", "阻止"},
        {"Penetration", "穿透"},
        {"Ignore", "忽略"},
        {"Trigger Key", "绑定键"},
        {"FOV", "FOV"},
        {"FOV Profile", "FOV 配置"},
        {"Radius", "半径"},
        {"Max Radius", "最大半径"},
        {"Min Radius", "最小半径"},
        {"Full Size At", "全尺寸距离"},
        {"Min Size At", "最小尺寸距离"},
        {"Advanced", "高级"},
        {"Fixed", "固定"},
        {"Distance", "按距离"},
        {"Target", "目标"},
        {"Near Distance", "近距离"},
        {"Near FOV", "近距 FOV"},
        {"Far Distance", "远距离"},
        {"Far FOV", "远距 FOV"},
        {"Acquisition Area", "捕获区域"},
        {"Target Point", "瞄准点"},
        {"Show FOV", "显示 FOV"},
        {"Visualization", "可视化"},
        {"Smoothing", "平滑"},
        {"Humanize", "拟人化"},
        {"Humanizer Tuning", "拟人化微调"},
        {"Humanizer Profile", "拟人化配置"},
        {"Motion", "运动"},
        {"Behavior", "行为"},
        {"Gravity", "重力"},
        {"Wind", "偏移"},
        {"Max Step", "最大步长"},
        {"Damping", "阻尼"},
        {"Reaction Min", "最小反应"},
        {"Reaction Max", "最大反应"},
        {"Curve", "曲线"},
        {"Overshoot Chance", "过冲概率"},
        {"Overshoot Amount", "过冲强度"},
        {"Jitter", "微抖"},
        {"Deadzone", "死区"},
        {"Hitboxes", "命中框"},
        {"Multi-Point", "多点"},
        {"Cap Points", "端点"},
        {"Side Points", "侧点"},
        {"Head Scale", "头部缩放"},
        {"Body Scale", "身体缩放"},
        {"Limbs Scale", "四肢缩放"},
        {"Prediction", "预测"},
        {"Max Horizon", "预测范围"},
        {"Acceleration", "考虑加速度"},
        {"RCS", "后坐力控制"},
        {"Start Bullet", "起始子弹"},
        {"Pitch Strength", "垂直强度"},
        {"Yaw Strength", "水平强度"},
        {"Humanization", "拟人化"},
        {"Response", "响应"},
        {"Gain Randomness", "力度随机"},
        {"Drift", "漂移"},
        {"Correction Time", "修正时间"},
        {"Smoothness", "平滑度"},
        {"Strength Variation", "力度变化"},
        {"Path Drift", "轨迹漂移"},
        {"Wall Policy", "穿墙策略"},
        {"Only Visible", "仅可见"},
        {"Shot Timing", "开枪时机"},
        {"Randomize", "随机化"},
        {"Outlier Chance", "离群概率"},
        {"Outlier Delay", "离群延迟"},
        {"Lethal Only", "仅致命伤害"},
        {"R8 Readiness", "R8 就绪"},
        {"Release Margin", "释放余量"},
        {"Key", "绑定键"},
        {"Visible Only", "仅可见目标"},
        {"Predictive", "预测"},
        {"Recoil Sync", "后坐力同步"},
        {"Auto Wall", "自动穿墙"},
        {"Min Damage", "最小伤害"},
        {"Draw FOV Circle", "绘制 FOV 圆"},
        {"Mode", "模式"},
        {"Interface Colors", "界面颜色"},
        {"Typography", "文字"},
        {"Primary Text", "主文本"},
        {"Muted Text", "次要文本"},
        {"Surfaces", "表面"},
        {"Menu Background", "菜单背景"},
        {"Controls", "控件"},
        {"Containers", "容器"},
        {"Popups", "弹窗"},
        {"Interaction", "交互"},
        {"Accent", "强调色"},
        {"Hover", "悬停"},
        {"Borders", "边框"},
        {"Seed Type", "种子类型"},
        {"Hitchance", "命中率"},
        {"Delay (ms)", "延迟 (ms)"},
        {"Reaction Time (ms)", "反应时间 (ms)"},
        {"Auto Stop", "自动急停"},
        {"Early Auto Stop", "提前自动急停"},
        {"Delay Before", "之前延迟"},
        {"Delay After", "之后延迟"},
        {"Randomize (+-)", "随机 (±)"},
        {"Inherit Global Settings", "继承全局设置"},

        // --- shared option values ---------------------------------------
        {"Advanced", "高级"},
        {"None", "无"},
        {"All", "全部"},
        {"Restricted", "受限"},
        {"Unrestricted", "不受限"},
        {"Head", "头部"},
        {"Body", "身体"},
        {"Arms", "手臂"},
        {"Legs", "腿部"},

        // --- visuals tabs -----------------------------------------------
        {"Players", "玩家"},
        {"Items", "掉落物"},
        {"Projectiles", "投掷物"},
        {"Bomb", "炸弹"},
        {"Radar", "雷达"},
        {"World", "世界"},
        {"Crosshair", "准星"},

        // --- expanded radar / crosshair ---------------------------------
        {"Player Names", "玩家名称"},
        {"Player Health", "玩家生命值"},
        {"Player Armor", "玩家护甲"},
        {"Player Weapon", "玩家武器"},
        {"Grenade Markers", "手雷标记"},
        {"Grenade Trajectories", "手雷轨迹"},
        {"Grenade Zones", "手雷区域"},
        {"Information Scale", "信息缩放"},
        {"Overlay Enemy Markers", "敌人标记"},
        {"Enemy Marker", "敌人标记"},
        {"View Direction", "视线方向"},
        {"Status Text", "状态文本"},
        {"Marker Scale", "标记缩放"},
        {"Text Outline", "文字描边"},
        {"HE Color", "HE 颜色"},
        {"Flash Color", "闪光颜色"},
        {"Smoke Color", "烟雾颜色"},
        {"Molotov Color", "燃烧瓶颜色"},
        {"Decoy Color", "诱饵颜色"},
        {"Line Thickness", "线条粗细"},
        {"End Point Size", "终点大小"},
        {"Fill Opacity", "填充透明度"},
        {"Outline Opacity", "轮廓透明度"},
        {"In-Game Avatars", "游戏内头像"},
        {"Copy Game Crosshair", "复制游戏准星"},
        {"Outline Color", "轮廓颜色"},
        {"Outline Thickness", "轮廓粗细"},

        // --- player esp -------------------------------------------------
        {"MASTER", "主要"},
        {"BOUNDING BOX", "方框"},
        {"DETAILS", "信息"},
        {"SKELETON & HITBOXES", "骨骼和命中框"},
        {"Enable Player ESP", "启用玩家透视"},
        {"Legit Sync", "合法同步"},
        {"Spectator Sync", "观战同步"},
        {"Direct Visibility", "直接可见"},
        {"Radar Spotted", "雷达发现"},
        {"Audible Sounds", "可听声音"},
        {"Radar Hold", "雷达持续时间"},
        {"Sound Hold", "声音持续时间"},
        {"Hearing Distance", "听力距离"},
        {"Pulse Minimum", "最小脉冲"},
        {"Pulse Maximum", "最大脉冲"},
        {"Pulse Period", "脉冲周期"},
        {"Show Box", "方框"},
        {"Style", "样式"},
        {"Full", "完整"},
        {"Cornered", "角落"},
        {"Corner Length", "角落长度"},
        {"Background Fill", "背景填充"},
        {"Box Visible Color", "方框：可见"},
        {"Box Occluded Color", "方框：遮挡"},
        {"Fill Visible Color", "填充：可见"},
        {"Fill Occluded Color", "填充：遮挡"},
        {"Show Name", "名称"},
        {"Show Weapon", "武器"},
        {"Ammo Indicator", "弹药指示器"},
        {"Exact Ammo Count", "精确弹药数量"},
        {"Empty Color", "空弹颜色"},
        {"Bomb Damage", "炸弹伤害"},
        {"Health Bar", "生命条"},
        {"Ammo Bar", "弹药条"},
        {"Info Flags", "信息标志"},
        {"Chams", "透视"},
        {"Antialiasing", "抗锯齿"},
        {"Model Glow", "模型发光"},
        {"Glow Color", "发光颜色"},
        {"Glow Radius", "发光半径"},
        {"Glow Strength", "发光强度"},
        {"Glow Layers", "发光层数"},
        {"Death Shatter", "死亡碎裂"},
        {"On Hit Chams", "命中透视"},
        {"Kill Particles", "击杀粒子"},
        {"Particle Color", "粒子颜色"},
        {"Particle Duration", "粒子持续时间"},
        {"Particle Size", "粒子大小"},
        {"Particle Count", "粒子数量"},
        {"On Shot Chams", "开枪透视"},
        {"Ghost Duration", "残影持续时间"},
        {"Ghost Appearance", "残影外观"},
        {"Occlusion", "遮挡"},
        {"Dynamic Doors", "动态门"},
        {"Smoke Occlusion", "烟雾遮挡"},
        {"Chams Visible", "透视：可见"},
        {"Chams Occluded", "透视：遮挡"},
        {"Show Skeleton", "骨骼"},
        {"Show Head Circle", "头部圆圈"},
        {"Show View Line", "视线"},
        {"Offscreen Arrows", "屏幕外箭头"},
        {"Arrow Color", "箭头颜色"},
        {"Arrow Size", "箭头大小"},
        {"Arrow Radius", "箭头半径"},
        {"Bloom Speed", "发光速度"},
        {"Minimum Glow", "最小发光"},
        {"Maximum Glow", "最大发光"},
        {"Threat Hitboxes", "命中框"},
        {"SOUND ESP", "声音"},
        {"Sound ESP", "声音"},
        {"Enable Sound ESP", "显示声音"},
        {"Ring Color", "圆环颜色"},
        {"Local Sync", "仅可听"},
        {"Duration", "持续时间"},
        {"Ring Radius", "圆环半径"},
        {"Audible Distance", "听觉范围"},
        {"Head Hitbox Color", "颜色：头部"},
        {"Body Hitbox Color", "颜色：身体"},
        {"Fill Alpha", "透明度"},

        // --- chams materials --------------------------------------------
        {"Material", "材质"},
        {"Color", "颜色"},
        {"Wireframe", "线框"},
        {"Roughness", "粗糙度"},
        {"Metalness", "金属度"},
        {"Exponent", "指数"},
        {"Falloff", "衰减"},
        {"Fresnel Filling", "菲涅尔填充"},
        {"Strength", "强度"},
        {"Speed", "速度"},
        {"Tint", "色调"},
        {"Solid", "实心"},
        {"Shaded", "带阴影"},
        {"Glow", "发光"},

        {"Glow Outline", "发光轮廓"},
        {"Iridescent", "彩虹"},
        {"Water Flow", "水流"},
        {"Glossy", "光泽"},

        // --- item esp ---------------------------------------------------
        {"SETTINGS", "设置"},
        {"FILTERS", "过滤器"},
        {"Enable Item ESP", "启用掉落物透视"},
        {"Max Distance", "距离"},
        {"Show Icon", "图标"},
        {"Show Item Name", "名称"},
        {"Rifles", "步枪"},
        {"SMGs", "冲锋枪"},
        {"Snipers", "狙击枪"},
        {"Pistols", "手枪"},
        {"Grenades", "手雷"},
        {"Utility", "道具"},

        // --- projectile esp ---------------------------------------------
        {"VISUAL ELEMENTS", "视觉元素"},
        {"COLORS", "颜色"},
        {"Enable Projectiles", "启用投掷物透视"},
        {"Display Mode", "显示模式"},
        {"Indicator", "指示器"},
        {"Text Only", "仅文本"},
        {"Show Text", "显示文本"},
        {"Effect Timer", "效果计时器"},
        {"Effect Timer Ring", "效果计时环"},
        {"Inferno Bounds", "燃烧瓶边界"},
        {"INDICATOR", "指示器"},
        {"Timer Full", "计时器：满"},
        {"Timer Low", "计时器：低"},
        {"Indicator Background", "指示器背景"},
        {"INFERNO GRADIENT", "燃烧瓶渐变"},
        {"Gradient Width", "渐变宽度"},
        {"Gradient Opacity", "渐变亮度"},
        {"HE Grenade", "高爆手雷"},
        {"Flashbang", "闪光弹"},
        {"Smoke", "烟雾弹"},
        {"Molotov", "燃烧瓶"},
        {"Decoy", "诱饵弹"},

        // --- bomb esp ---------------------------------------------------
        {"STATES", "状态"},
        {"SAFE ZONE (BAKED)", "安全区"},
        {"Enable Bomb ESP", "启用炸弹透视"},
        {"Show Carrier", "携带者"},
        {"Show Planted", "已安放"},
        {"Planted Color", "安放颜色"},
        {"Defusing Color", "拆弹颜色"},
        {"Panel Background", "面板背景"},
        {"World Timer Ring", "世界计时环"},
        {"World Timer", "世界计时器"},
        {"Bomb Info Panel", "炸弹信息面板"},
        {"Timer Color", "计时器颜色"},
        {"Safe Zone Contour", "安全区轮廓"},
        {"Zone Color", "区域颜色"},
        {"Gradient Bands", "等值线"},
        {"Band Step", "等值线步长"},

        // --- radar / world ----------------------------------------------
        {"RADAR OVERLAY", "雷达"},
        {"Overlay Enemy Markers", "敌人标记"},
        {"NO FLASH (WIREFRAME)", "无闪光（线框）"},
        {"Enable Visual No Flash", "启用无闪光"},
        {"Render Distance", "渲染距离"},
        {"Dimming Overlay Color", "变暗覆盖颜色"},
        {"Wireframe Color", "线框颜色"},
        {"NO SMOKE (WIREFRAME)", "无烟雾（线框）"},
        {"Enable Visual No Smoke", "启用无烟雾"},
        {"Smoke Wireframe Color", "烟雾线框颜色"},

        // --- crosshair --------------------------------------------------
        {"CROSSHAIR SETTINGS", "准星"},
        {"Enable Crosshair", "启用准星"},
        {"Weapon Sync", "武器同步"},
        {"Draw Dot", "点"},
        {"Draw Lines", "线"},
        {"T-Style", "T 形"},
        {"Length", "长度"},
        {"Gap", "间隙"},
        {"Thickness", "粗细"},
        {"Draw Outline", "描边"},
        {"Primary Color", "颜色"},
        {"Penetration Indicator", "穿透指示器"},
        {"Can Penetrate", "可穿透"},
        {"Cannot Penetrate", "不可穿透"},

        // --- misc tabs --------------------------------------------------
        {"General", "通用"},
        {"Movement", "移动"},
        {"Effects", "效果"},
        {"Overlay", "叠加层"},
        {"Lua API", "Lua API"},
        {"Configs", "配置"},
        {"LUA RUNTIME", "LUA 运行时"},
        {"SCRIPTS", "脚本"},
        {"Enable Lua API", "启用 Lua API"},
        {"Script Directory", "脚本目录"},
        {"Open Folder", "打开文件夹"},
        {"Load Lua Script", "加载 Lua 脚本"},
        {"Copy link", "复制链接"},
        {"Copy Path", "复制路径"},
        {"Discover Scripts", "刷新列表"},
        {"Refresh", "刷新"},
        {"No Lua scripts found", "未找到 Lua 脚本"},
        {"Copy scripts into the Lua directory", "将脚本复制到 Lua 目录"},
        {"Autoload", "自动加载"},
        {"Hot Reload", "热重载"},
        {"Status", "状态"},
        {"Runtime", "运行"},
        {"Last Error", "最后错误"},
        {"Reload Script", "重新加载脚本"},
        {"Reload", "重新加载"},

        // --- misc: general ----------------------------------------------
        {"AUTOMATION", "自动化"},
        {"Auto Accept Match", "自动接受比赛"},
        {"GRENADES", "手雷"},
        {"LINEUP HELPER", "投掷物助手"},
        {"GRENADE ASSIST", "手雷辅助"},
        {"TRAJECTORY", "轨迹"},
        {"Lineup Helper", "投掷物助手"},
        {"Draw Distance", "绘制距离"},
        {"Marker Distance", "标记距离"},
        {"Stand Radius", "站位半径"},
        {"Release Radius", "释放精度"},
        {"Height Tolerance", "高度容差"},
        {"Show Throw Type", "投掷类型"},
        {"Show Distance", "距离"},
        {"Plaque Background", "标牌背景"},
        {"Plaque Text", "标牌文本"},
        {"Plaque Accent", "标牌强调色"},
        {"Stand Marker", "站位标记"},
        {"Stand Marker Active", "站位标记（激活）"},
        {"Aim Marker", "瞄准标记"},
        {"Lineup Aim Assist", "投掷物瞄准辅助"},
        {"Aim Key", "辅助绑定键"},
        {"Auto Release", "自动投掷"},
        {"Lock Threshold", "锁定阈值"},
        {"Settle Time", "稳定时间"},
        {"Enemy Aim Assist", "手雷对敌辅助"},
        {"Activation Key", "绑定键"},
        {"Target FOV", "搜索 FOV"},
        {"Trajectory Preview", "轨迹预览"},
        {"Local Prediction Only", "仅本地投掷物"},
        {"Line Style", "线条样式"},
        {"Line Color", "线条颜色"},
        {"Line Thickness", "线条粗细"},
        {"Bloom", "发光"},
        {"Bloom Color", "发光颜色"},
        {"Bloom Radius", "发光半径"},
        {"Bounce Points", "弹跳点"},
        {"End Point", "终点"},
        {"Point Color", "点颜色"},
        {"Point Size", "点大小"},
        {"ENGINE", "引擎"},
        {"FPS Limiter", "FPS 限制"},
        {"Maximum FPS", "最大 FPS"},
        {"INTERFACE", "界面"},
        {"LANGUAGE", "语言"},
        {"Language", "语言"},
        {"DPI Scale", "DPI 缩放"},

        // --- misc: movement ---------------------------------------------
        {"BUNNY HOP", "连跳"},
        {"EDGE JUMP", "边缘跳跃"},
        {"Enable Bunny Hop", "启用连跳"},
        {"Enable Edge Jump", "启用边缘跳跃"},

        // --- misc: effects ----------------------------------------------
        {"BULLET TRACERS", "弹道"},
        {"Enable Bullet Tracers", "启用弹道"},
        {"Tracer Color", "弹道颜色"},
        {"Fade Duration", "淡出时间"},
        {"Max Tracers", "最大弹道数"},
        {"Bloom Effect", "发光效果"},
        {"Draw Impact Cubes", "命中标记"},
        {"Draw Trajectory Line", "轨迹线"},
        {"Cube Size", "标记大小"},
        {"Fade Near", "近处淡出"},
        {"Fade Far", "远处淡出"},

        // --- misc: overlay ----------------------------------------------
        {"CAPTURE", "屏幕捕获"},
        {"OBS Bypass", "OBS 绕过"},
        {"WATERMARK", "水印"},
        {"Show Watermark", "显示"},
        {"Show Ping", "Ping"},
        {"Show Loss", "丢包"},
        {"Show CPU Load", "CPU 负载"},
        {"Show FPS", "FPS"},

        {"SPECTATOR LIST", "观察者"},
        {"Show Spectators", "显示"},
        {"EVENT LOG", "事件日志"},
        {"Event Log", "事件日志"},
        {"Show Event Log", "显示日志"},
        {"Maximum Entries", "记录数量"},
        {"Events", "事件"},
        {"Shots", "射击"},
        {"Hits", "命中"},
        {"Kills", "击杀"},
        {"Misses", "未命中"},
        {"Blocked", "拦截"},
        {"Info", "信息"},
        {"ACTIVE BINDS", "激活绑定"},
        {"Active Binds", "激活绑定"},
        {"Show Active Binds", "显示激活绑定"},
        {"Always On Binds", "显示始终开启"},
        {"Hold Binds", "显示按住"},
        {"Toggle Binds", "显示切换"},
        {"BOMB PANEL", "炸弹面板"},
        {"Show Bomb Info", "显示炸弹信息"},
        {"No active entries", "无激活记录"},
        {"Spectators", "观察者"},

        {"Steam Avatars", "Steam 头像"},
        {"  fixed camera", "  固定相机"},
        {"  first person", "  第一人称"},
        {"  third person", "  第三人称"},
        {"  free camera", "  自由相机"},

        // --- misc: configs ----------------------------------------------
        {"CFG FILE", "配置"},
        {"File Name", "文件名"},
        {"Export Named CFG", "保存"},
        {"Save As...", "另存为..."},
        {"Open CFG", "加载"},
        {"Browse...", "浏览..."},

        // --- esp editor -------------------------------------------------
        {"ESP EDITOR", "透视编辑器"},
        {"PREVIEW UNAVAILABLE", "预览不可用"},

        {"Manual lineup", "手动投掷"},
        {"Hold {}, release", "按住 {}, 释放"},
        {"Hold {}, {}, release", "按住 {}, {}, 释放"},
        {"LMB", "左键"},
        {"RMB", "右键"},
        {"LMB+RMB", "左键+右键"},
        {"m", "米"},

        {"Jump+Throw", "跳跃投掷"},
        {"W+Jump+Throw", "W+跳跃投掷"},
        {"Run+Jump+Throw", "跑+跳跃投掷"},
        {"Walk+Jump+Throw", "走+跳跃投掷"},
        {"Crouch+Jump+Throw", "蹲+跳跃投掷"},
        {"Crouch+W+Jump+Throw", "蹲+W+跳跃投掷"},
        {"Crouch+Run+Jump+Throw", "蹲+跑+跳跃投掷"},
        {"WJump+Throw", "W+跳跃投掷"},
        {"Jump+Throw LRMB", "跳跃投掷 左键+右键"},
        {"Jump+Throw RMB", "跳跃投掷 右键"},
        {"W+Jump+Throw LRMB", "W+跳跃投掷 左键+右键"},
        {"W+Jump+Throw RMB", "W+跳跃投掷 右键"},
        {"Run+Jump+Trhow", "跑+跳跃投掷"},
        {"W+Jump+Throwv", "W+跳跃投掷"},
        {"Throw", "投掷"},
        {"Throw LRMB", "投掷 左键+右键"},
        {"Throw RMB", "投掷 右键"},
        {"Throw (crouch)", "蹲下投掷"},
        {"Throw (break glass)", "投掷（破窗）"},
        {"Run+Thorw", "跑+投掷"},
        {"Run+Throw", "跑+投掷"},
        {"Crouch+Run+Throw", "蹲+跑+投掷"},
        {"Go Left then W+Jump+Throw", "左移，然后 W+跳跃投掷"},
        {"Go Right then W+Jump+Throw", "右移，然后 W+跳跃投掷"},
        {"Complex, move left and back and jumpthrow while running",
         "复杂：左后移动，跑动中跳跃投掷"},
        {"Insta Window (no autothrow)", "秒窗（无自动投掷）"},
        {"Insta Long Door (no autothrow)", "秒长门（无自动投掷）"},

        // Fallback tokens, used for any combination not spelled out above.
        {"Jump", "跳跃"},
        {"Crouch", "蹲下"},
        {"Run", "跑"},
        {"Walk", "走"},
        {"Step", "走"},
        {"Forward", "前进"},
        // The source table spells these wrong; kept verbatim as keys.
        {"Trhow", "投掷"},
        {"Thorw", "投掷"},
        {"Throwv", "投掷"},
    };

    return table;
}

} // namespace

void set(id value)
{
    if (value >= id::en && value < id::count)
    {
        g_current.store(value, std::memory_order_relaxed);
    }
}

id current()
{
    return g_current.load(std::memory_order_relaxed);
}

const char *code(id value)
{
    return value == id::ru ? "RU" : "EN";
}

const char *tr(const char *english)
{
    if (!english || current() == id::en)
    {
        return english;
    }

    const auto &table = chinese();
    const auto it = table.find(std::string_view{english});
    return it == table.end() ? english : it->second;
}

std::string_view tr(std::string_view english)
{
    if (current() == id::en)
    {
        return english;
    }

    const auto &table = chinese();
    const auto it = table.find(english);
    return it == table.end() ? english : std::string_view{it->second};
}

} // namespace render::localization
